name: "Super linter"
on:
  pull_request:
    branches: [master, main]
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: 'Lint Code Base'
      uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # needed to get access to PR​