on:
  # push:
  workflow_dispatch:

jobs:
  hadolint:
    name: "Hadolint scan"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    # don't execute this workflow for dependabot pr
    if: (github.actor != 'dependabot[bot]')
    steps:
    - uses: actions/checkout@v2 
    - uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: ./Dockerfile
    - name: "Upload analysis results to GitHub"
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: hadolint-results.sarif
        wait-for-processing: true