name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    container: # Use a container
      image: returntocorp/semgrep:1.1.0
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: "Checkout source"
        uses: actions/checkout@v3
      - name: "Execute semgrep"
        run: semgrep ci
        env:
         # Specify the ruleset to use
          SEMGREP_RULES: p/default
